# Generated by Django 4.2.6 on 2023-10-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('waitingapproval', 'Waiting approval'), ('active', 'active'), ('deleted', 'Deleted')], default='active', max_length=50),
        ),
    ]
